
import sys
from pathlib import Path
import numpy as np

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from core.ocean.Liwc import analyse_text

def calculate_linguistic_fidelity(generated_review, target_liwc):
    """
    Calculates the fidelity (similarity) between a generated review's 
    linguistic features and a target persona's LIWC features.
    
    Args:
        generated_review: The text generated by the LLM
        target_liwc: A dictionary of LIWC features from the user's profile
                     (e.g., as stored in 'liwc_features' in user_profiles.csv)
                     
    Returns:
        A dictionary containing:
          - fidelity_score: 0.0 to 1.0 (1.0 being identical patterns)
          - feature_deltas: Differences per feature
          - match_summary: Human-readable assessment
    """
    if not generated_review or not target_liwc:
        return {"fidelity_score": 0.0, "match_summary": "Missing data for evaluation"}

    # 1. Analyse the generated text
    gen_liwc = analyse_text(generated_review)
    
    # 2. Select keys to compare (focus on patterns, not absolute counts)
    # These match the keys found in user_profiles.csv and core/ocean/Liwc.py
    compare_keys = [
        "avg_sentence_len",
        "pos_affect_ratio",
        "neg_affect_ratio",
        "certainty_ratio",
        "hedge_ratio",
        "analytical_ratio",
        "social_ratio",
        "self_ref_ratio",
        "exclamation_rate"
    ]
    
    deltas = {}
    weights = {
        "avg_sentence_len": 0.15,
        "pos_affect_ratio": 0.15,
        "neg_affect_ratio": 0.15,
        "certainty_ratio": 0.10,
        "hedge_ratio": 0.10,
        "analytical_ratio": 0.10,
        "social_ratio": 0.05,
        "self_ref_ratio": 0.05,
        "exclamation_rate": 0.15
    }
    
    score_components = []
    
    for key in compare_keys:
        target_val = target_liwc.get(key, 0.0)
        gen_val = gen_liwc.get(key, 0.0)
        
        # Calculate absolute difference
        diff = abs(target_val - gen_val)
        deltas[key] = round(diff, 4)
        
        # Calculate similarity for this feature
        # We use a decaying similarity: 1 / (1 + diff/scale)
        # Scale determines how quickly the score drops
        scale = 5.0 if key == "avg_sentence_len" else 0.05
        feature_sim = 1.0 / (1.0 + (diff / scale))
        
        score_components.append(feature_sim * weights[key])

    fidelity_score = round(sum(score_components), 4)
    
    # Human readable summary
    if fidelity_score > 0.85:
        summary = "Excellent voice match: linguistic patterns are nearly identical."
    elif fidelity_score > 0.70:
        summary = "Good voice match: follows the user's general writing style."
    elif fidelity_score > 0.50:
        summary = "Fair voice match: some stylistic patterns missed."
    else:
        summary = "Poor voice match: linguistic fingerprint differs significantly."
        
    return {
        "fidelity_score": fidelity_score,
        "feature_deltas": deltas,
        "match_summary": summary,
        "generated_features": gen_liwc,
        "target_features": target_liwc
    }

if __name__ == "__main__":
    # Self-test
    print("Testing Linguistic Fidelity Scorer...")
    
    sample_target = {
        "avg_sentence_len": 22.0,
        "pos_affect_ratio": 0.08,
        "neg_affect_ratio": 0.01,
        "exclamation_rate": 0.05,
        "certainty_ratio": 0.02
    }
    
    sample_gen = "Wow! I am absolutely thrilled with this. It is clearly the best thing I've bought all year. Every single detail is just perfect."
    
    result = calculate_linguistic_fidelity(sample_gen, sample_target)
    print(f"Fidelity Score: {result['fidelity_score']}")
    print(f"Summary: {result['match_summary']}")
    print(f"Deltas: {result['feature_deltas']}")
