# Generated by Django 5.2.14 on 2026-05-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendationcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('sub_category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('item_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, db_index=True, max_length=500)),
                ('text', models.TextField()),
                ('rating', models.FloatField()),
                ('ocean_o', models.FloatField(default=0.5)),
                ('ocean_c', models.FloatField(default=0.5)),
                ('ocean_e', models.FloatField(default=0.5)),
                ('ocean_a', models.FloatField(default=0.5)),
                ('ocean_n', models.FloatField(default=0.5)),
                ('generosity_score', models.FloatField(default=0.5)),
                ('avg_review_length', models.FloatField(default=0.0)),
                ('source', models.CharField(default='amazon', max_length=50)),
            ],
            options={
                'db_table': 'review_bank',
                'indexes': [models.Index(fields=['category', 'ocean_a'], name='review_bank_categor_7680c5_idx'), models.Index(fields=['category', 'title'], name='review_bank_categor_eeead9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserReviewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(default='amazon', max_length=50)),
                ('dominant_archetype', models.CharField(db_index=True, max_length=50)),
                ('secondary_archetype', models.CharField(blank=True, max_length=50)),
                ('archetype_confidence', models.FloatField(default=0.0)),
                ('ocean_o', models.FloatField(default=0.5)),
                ('ocean_c', models.FloatField(default=0.5)),
                ('ocean_e', models.FloatField(default=0.5)),
                ('ocean_a', models.FloatField(default=0.5)),
                ('ocean_n', models.FloatField(default=0.5)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('generosity_score', models.FloatField(default=0.5)),
                ('avg_review_length', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'user_review_profiles',
                'indexes': [models.Index(fields=['dominant_archetype', 'ocean_a'], name='user_review_dominan_09b8b7_idx')],
            },
        ),
    ]
