# Generated by Django 5.2.14 on 2026-05-12 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_reviewbank_userreviewprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationcache',
            unique_together={('user', 'category')},
        ),
    ]
