# Generated by Django 5.2.14 on 2026-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_recommendationcache_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('genres', models.JSONField(default=list)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('emotional_tone', models.TextField(blank=True)),
                ('audience_summary', models.TextField(blank=True)),
                ('top_praises', models.JSONField(default=list)),
                ('top_complaints', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
