# Generated by Django 5.2.14 on 2026-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='audience_summary',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='top_complaints',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='region',
            field=models.CharField(choices=[('hollywood', 'Hollywood'), ('nollywood', 'Nollywood')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
