# Generated by Django 5.2.14 on 2026-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_movie_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='top_critics',
            field=models.JSONField(default=list),
        ),
    ]
