# Generated by Django 5.2.14 on 2026-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_movie_top_critics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_id', models.CharField(db_index=True, max_length=50)),
                ('item_title', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('affinity_score', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'archetype_affinities',
                'indexes': [models.Index(fields=['archetype_id', 'category', '-affinity_score'], name='archetype_a_archety_9ae47e_idx')],
                'unique_together': {('archetype_id', 'item_title', 'category')},
            },
        ),
    ]
