# Generated by Django 5.2.14 on 2026-05-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('apps', 'Apps'), ('products', 'Products'), ('books', 'Books'), ('movies', 'Movies'), ('restaurants', 'Restaurants')], max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('optional_note', models.TextField(blank=True)),
                ('predicted_rating', models.IntegerField()),
                ('rating_confidence', models.CharField(blank=True, max_length=20)),
                ('reasoning_shown', models.TextField(blank=True)),
                ('generated_review', models.TextField()),
                ('edited_review', models.TextField(blank=True)),
                ('feedback_score', models.CharField(blank=True, choices=[('off', 'Off'), ('close', 'Close'), ('spot_on', 'Spot On')], max_length=20)),
                ('provider', models.CharField(default='gemini', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
