# Generated by Django 5.2.14 on 2026-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actual_user_rating',
            field=models.IntegerField(blank=True, help_text='The rating the user actually gave', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rouge_l_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_written_review',
            field=models.TextField(blank=True, help_text="The user's own review for comparison"),
        ),
    ]
