# Generated by Django 5.2.14 on 2026-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_actual_user_rating_review_rouge_l_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bert_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
